### ISSUE TITLE
vaccination-notify-master/scripts/track.py  NCZI response  404 NOT FOUND

### ISSUE THREAD

**Issue by b1naryc0m** [slovensko-help/vaccination-notify#1]
Hello,
is this NCZI API validate_drivein_times_vacc still working ? Always got response 404 not found.

ENVIRONMENT:
```
Python 3.8.5
Linux Mint - 5.4.0-66-generic
requirements.txt - Installed
places.py , groups.py - Updated
```

python3 track.py -n +421123456789 -c Bratislava -f 5

```
[*] Will track places [*]
 * Vakcína ASTRA Poliklinika Mlynská dolina - Bratislava (2062)
 * Vakcína CINRE, Bratislava - Bratislava (815)
 * Vakcína Hedak s.r.o. Poliklinika Mýtna, Bratislava - Bratislava (885)
 * Vakcína Med zariadenie Mlynská Dolina, Bratislava - Bratislava (1686)
 * Vakcína Ružinovská poliklinika, Bratislava - Bratislava (836)
 * Vakcína Sanatórium Koch, Bratislava - Bratislava (798)
 * Vakcína UNB Antolská, Bratislava (1) - Bratislava (571)
 * Vakcína UNB Antolská, Bratislava (2) - Bratislava (807)
 * Vakcína UNB Kramáre, Bratislava (1) - Bratislava (572)
 * Vakcína UNB Kramáre, Bratislava (2) - Bratislava (806)
 * Vakcína UNB Ružinov, Bratislava (1) - Bratislava (573)
 * Vakcína UNB Ružinov, Bratislava (2) - Bratislava (745)
[*] Will message numbers [*]
 * +421123456789
[ ] Querying .....

Traceback (most recent call last):
  File "track.py", line 74, in <module>
    main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "track.py", line 44, in main
    js = r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
nano vaccination-notify-master/scripts/track.py

```
        click.echo("[ ] Querying .....")
        free = {aplace["city"]: 0 for aplace in places}
        for aplace in places:
            r = requests.post(QUERY_URL, json={"drivein_id": str(aplace["id"])})


+++      click.echo("\n---------------------------------- \n")
+++      click.echo(r)
+++      click.echo("\n---------------------------------- \n")

            js = r.json()
            for line in js["payload"]:
``` 

Console output: 
```
[ ] Querying .....

---------------------------------- 

<Response [404]>

---------------------------------- 
```

curl -v -X POST https://mojeezdravie.nczisk.sk/api/v1/web/validate_drivein_times_vacc -H "Content-Type: application/json" -d "{\"drivein_id\": \"798\"}"

```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 94.124.148.93:443...
* TCP_NODELAY set
* Connected to mojeezdravie.nczisk.sk (94.124.148.93) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=SK; L=BRATISLAVA; O=N�rodn� Centrum Zdravotn�ckych Inform�ci�; CN=*.nczisk.sk
*  start date: Jun 17 00:00:00 2020 GMT
*  expire date: Jul 14 12:00:00 2022 GMT
*  subjectAltName: host "mojeezdravie.nczisk.sk" matched cert's "*.nczisk.sk"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=Thawte RSA CA 2018
*  SSL certificate verify ok.
> POST /api/v1/web/validate_drivein_times_vacc HTTP/1.1
> Host: mojeezdravie.nczisk.sk
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 21
> 
* upload completely sent off: 21 out of 21 bytes
* Mark bundle as not supporting multiuse


< HTTP/1.1 404 Not Found



< Date: Sun, 07 Mar 2021 11:12:21 GMT
< Server: Apache
< X-FRAME-OPTIONS: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< Vary: User-Agent
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host mojeezdravie.nczisk.sk left intact
```

**Comment by J08nY** [comment]
Hi there,
it appears that NCZI took that endpoint down and now there is only the aggregate endpoint:

    https://mojeezdravie.nczisk.sk/api/v1/web/get_all_drivein_times_vacc
or its cached variant at:

    https://data.korona.gov.sk/ncziapi/get_all_drivein_times_vacc
which is a GET request endpoint without query parameters that returns a rather large JSON body of all the vaccination places and their free capacity.

The scripts for text messages using twilio are outdated and no longer work, they are kept here just for posterity.
